USE [Automate_Everything_With_Python]

CREATE TABLE [dbo].[Payors](
	[PayorID] [nvarchar](20) NOT NULL,
	[Payor] [nvarchar](75) NULL,
 CONSTRAINT [PK_Payor] PRIMARY KEY CLUSTERED 
(
	[PayorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

